export const defaultForecast = {
  location: {
    name: 'Moscow',
    region: 'Moscow City',
    country: 'Russia',
    lat: 55.75,
    lon: 37.62,
    tz_id: 'Europe/Moscow',
    localtime_epoch: 1657228046,
    localtime: '2022-07-08 0:07',
  },
  current: {
    last_updated_epoch: 1657224000,
    last_updated: '2022-07-07 23:00',
    temp_c: 18.0,
    temp_f: 64.4,
    is_day: 0,
    condition: {
      text: 'Переменная облачность',
      icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
      code: 1003,
    },
    wind_mph: 9.4,
    wind_kph: 15.1,
    wind_degree: 270,
    wind_dir: 'W',
    pressure_mb: 1015.0,
    pressure_in: 29.97,
    precip_mm: 0.4,
    precip_in: 0.02,
    humidity: 83,
    cloud: 75,
    feelslike_c: 18.0,
    feelslike_f: 64.4,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 9.4,
    gust_kph: 15.1,
  },
  forecast: {
    forecastday: [
      {
        date: '2022-07-08',
        date_epoch: 1657238400,
        day: {
          maxtemp_c: 25.8,
          maxtemp_f: 78.4,
          mintemp_c: 15.8,
          mintemp_f: 60.4,
          avgtemp_c: 20.5,
          avgtemp_f: 68.9,
          maxwind_mph: 7.4,
          maxwind_kph: 11.9,
          totalprecip_mm: 2.4,
          totalprecip_in: 0.09,
          avgvis_km: 9.9,
          avgvis_miles: 6.0,
          avghumidity: 64.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 70,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Местами дождь',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: '03:57 AM',
          sunset: '09:12 PM',
          moonrise: '02:41 PM',
          moonset: '12:16 AM',
          moon_phase: 'First Quarter',
          moon_illumination: '63',
        },
        hour: [
          {
            time_epoch: 1657227600,
            time: '2022-07-08 00:00',
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 0,
            condition: {
              text: 'Местами дождь',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 347,
            wind_dir: 'NNW',
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 89,
            cloud: 86,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 0,
            chance_of_rain: 70,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1.0,
          },
          {
            time_epoch: 1657231200,
            time: '2022-07-08 01:00',
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 0,
            condition: {
              text: 'Местами дождь',
              icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
              code: 1063,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 353,
            wind_dir: 'N',
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 89,
            cloud: 78,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 16.1,
            heatindex_f: 61.0,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 1.0,
          },
          {
            time_epoch: 1657234800,
            time: '2022-07-08 02:00',
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: 'Небольшой ливневый дождь',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 344,
            wind_dir: 'NNW',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 1.6,
            precip_in: 0.06,
            humidity: 88,
            cloud: 98,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 13.8,
            dewpoint_f: 56.8,
            will_it_rain: 0,
            chance_of_rain: 70,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1.0,
          },
          {
            time_epoch: 1657238400,
            time: '2022-07-08 03:00',
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: 'Облачно',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 7,
            wind_dir: 'N',
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 83,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1.0,
          },
          {
            time_epoch: 1657242000,
            time: '2022-07-08 04:00',
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 1,
            condition: {
              text: 'Пасмурно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 7,
            wind_dir: 'N',
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 100,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 4.0,
          },
          {
            time_epoch: 1657245600,
            time: '2022-07-08 05:00',
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: 'Местами дождь',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 355,
            wind_dir: 'N',
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 84,
            cloud: 62,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 4.0,
          },
          {
            time_epoch: 1657249200,
            time: '2022-07-08 06:00',
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 354,
            wind_dir: 'N',
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 32,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 12.8,
            dewpoint_f: 55.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 5.0,
          },
          {
            time_epoch: 1657252800,
            time: '2022-07-08 07:00',
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 0,
            wind_dir: 'N',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 27,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 12.4,
            dewpoint_f: 54.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 5.0,
          },
          {
            time_epoch: 1657256400,
            time: '2022-07-08 08:00',
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 34,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 12.0,
            dewpoint_f: 53.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 5.0,
          },
          {
            time_epoch: 1657260000,
            time: '2022-07-08 09:00',
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 23,
            wind_dir: 'NNE',
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 28,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 11.9,
            dewpoint_f: 53.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 5.0,
          },
          {
            time_epoch: 1657263600,
            time: '2022-07-08 10:00',
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 19,
            wind_dir: 'NNE',
            pressure_mb: 1017.0,
            pressure_in: 30.03,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 31,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 11.9,
            dewpoint_f: 53.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 6.0,
          },
          {
            time_epoch: 1657267200,
            time: '2022-07-08 11:00',
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 15,
            wind_dir: 'NNE',
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 36,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
            uv: 6.0,
          },
          {
            time_epoch: 1657270800,
            time: '2022-07-08 12:00',
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 5,
            wind_dir: 'N',
            pressure_mb: 1016.0,
            pressure_in: 30.01,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 47,
            cloud: 51,
            feelslike_c: 25.3,
            feelslike_f: 77.5,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 25.3,
            heatindex_f: 77.5,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
            uv: 6.0,
          },
          {
            time_epoch: 1657274400,
            time: '2022-07-08 13:00',
            temp_c: 25.1,
            temp_f: 77.2,
            is_day: 1,
            condition: {
              text: 'Облачно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 357,
            wind_dir: 'N',
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 80,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 25.1,
            windchill_f: 77.2,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6.0,
          },
          {
            time_epoch: 1657278000,
            time: '2022-07-08 14:00',
            temp_c: 25.2,
            temp_f: 77.4,
            is_day: 1,
            condition: {
              text: 'Облачно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 345,
            wind_dir: 'NNW',
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 78,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 25.2,
            windchill_f: 77.4,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6.0,
          },
          {
            time_epoch: 1657281600,
            time: '2022-07-08 15:00',
            temp_c: 25.8,
            temp_f: 78.4,
            is_day: 1,
            condition: {
              text: 'Облачно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 338,
            wind_dir: 'NNW',
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 44,
            cloud: 68,
            feelslike_c: 26.1,
            feelslike_f: 79.0,
            windchill_c: 25.8,
            windchill_f: 78.4,
            heatindex_c: 26.1,
            heatindex_f: 79.0,
            dewpoint_c: 12.5,
            dewpoint_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6.0,
          },
          {
            time_epoch: 1657285200,
            time: '2022-07-08 16:00',
            temp_c: 25.7,
            temp_f: 78.3,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 329,
            wind_dir: 'NNW',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 43,
            feelslike_c: 26.0,
            feelslike_f: 78.8,
            windchill_c: 25.7,
            windchill_f: 78.3,
            heatindex_c: 26.0,
            heatindex_f: 78.8,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
            uv: 7.0,
          },
          {
            time_epoch: 1657288800,
            time: '2022-07-08 17:00',
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 322,
            wind_dir: 'NW',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 44,
            cloud: 32,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 7.0,
          },
          {
            time_epoch: 1657292400,
            time: '2022-07-08 18:00',
            temp_c: 24.5,
            temp_f: 76.1,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 335,
            wind_dir: 'NNW',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 41,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 24.5,
            windchill_f: 76.1,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 12.6,
            dewpoint_f: 54.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 6.0,
          },
          {
            time_epoch: 1657296000,
            time: '2022-07-08 19:00',
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: 'Переменная облачность',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 0,
            wind_dir: 'N',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 46,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 6.0,
          },
          {
            time_epoch: 1657299600,
            time: '2022-07-08 20:00',
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 1,
            condition: {
              text: 'Солнечно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 24,
            wind_dir: 'NNE',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 20,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 21.0,
            heatindex_f: 69.8,
            dewpoint_c: 12.7,
            dewpoint_f: 54.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 6.0,
          },
          {
            time_epoch: 1657303200,
            time: '2022-07-08 21:00',
            temp_c: 20.0,
            temp_f: 68.0,
            is_day: 1,
            condition: {
              text: 'Солнечно',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 25,
            wind_dir: 'NNE',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 16,
            feelslike_c: 20.0,
            feelslike_f: 68.0,
            windchill_c: 20.0,
            windchill_f: 68.0,
            heatindex_c: 20.0,
            heatindex_f: 68.0,
            dewpoint_c: 12.7,
            dewpoint_f: 54.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 6.0,
          },
          {
            time_epoch: 1657306800,
            time: '2022-07-08 22:00',
            temp_c: 19.5,
            temp_f: 67.1,
            is_day: 0,
            condition: {
              text: 'Ясно',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 34,
            wind_dir: 'NE',
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 18,
            feelslike_c: 19.5,
            feelslike_f: 67.1,
            windchill_c: 19.5,
            windchill_f: 67.1,
            heatindex_c: 19.5,
            heatindex_f: 67.1,
            dewpoint_c: 12.8,
            dewpoint_f: 55.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1.0,
          },
          {
            time_epoch: 1657310400,
            time: '2022-07-08 23:00',
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 0,
            condition: {
              text: 'Ясно',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 53,
            wind_dir: 'NE',
            pressure_mb: 1016.0,
            pressure_in: 29.99,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 18,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 13.0,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};

export const defaultWeather = {
  location: {
    name: 'London',
    region: 'City of London, Greater London',
    country: 'United Kingdom',
    lat: 51.52,
    lon: -0.11,
    tz_id: 'Europe/London',
    localtime_epoch: 1657203524,
    localtime: '2022-07-07 15:18',
  },
  current: {
    last_updated_epoch: 1657203300,
    last_updated: '2022-07-07 15:15',
    temp_c: 23.0,
    temp_f: 73.4,
    is_day: 1,
    condition: {
      text: 'Переменная облачность',
      icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
      code: 1003,
    },
    wind_mph: 8.1,
    wind_kph: 13.0,
    wind_degree: 350,
    wind_dir: 'N',
    pressure_mb: 1030.0,
    pressure_in: 30.42,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 44,
    cloud: 75,
    feelslike_c: 23.9,
    feelslike_f: 75.0,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 7.0,
    gust_mph: 9.6,
    gust_kph: 15.5,
  },
};
